# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: logpoop 1.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "logpoop"
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Billy Reisinger"]
  s.date = "2014-06-03"
  s.description = "This gem installs a script called 'logpoop' that, when run, fills up your active terminal sessions with crap (so that you look really busy). "
  s.email = "billy.reisinger@gmail.com"
  s.executables = ["logpoop"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/logpoop",
    "lib/logpoop.rb",
    "lib/logpoop/poops/five.poop",
    "lib/logpoop/poops/four.poop",
    "lib/logpoop/poops/one.poop",
    "lib/logpoop/poops/three.poop",
    "lib/logpoop/poops/two.poop",
    "lib/logpoop/runner/context.rb",
    "lib/logpoop/runner/make.rb",
    "lib/logpoop/runner/multi_tail.rb",
    "lib/logpoop/runner/poop.rb",
    "lib/logpoop/runner/test_run.rb",
    "lib/logpoop/simulator/base.rb",
    "lib/logpoop/simulator/make.rb",
    "lib/logpoop/simulator/tail_eff.rb",
    "lib/logpoop/simulator/test_run.rb",
    "logpoop.gemspec",
    "test/helper.rb",
    "test/test_logpoop.rb"
  ]
  s.homepage = "http://github.com/unclebilly/logpoop"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Quick, look busy! Print some poop in your terminals!"
  s.test_files = [
    "test/helper.rb",
    "test/test_logpoop.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
  end
end

